name: Daily Script Runner

permissions:
  contents: write

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight
  workflow_dispatch:

jobs:
  run-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Set up Python
        run: uv python install # Installs the Python version specified project

      - name: Install dependencies
        run: uv sync # Installs all core dependencies from pyproject.toml and uv.lock

      - name: Run update_repo_downloads_stats.py
        run: |
          uv run src/update_repo_downloads_stats.py

      - name: Run generate_total_downloads_chart.py
        run: |
          uv run src/charts/generate_total_downloads_chart.py

      - name: Run generate_top_repos_chart.py
        run: |
          uv run src/charts/generate_top_repos_chart.py

      - name: Commit changes
        run: |
          git config --local user.email 'github-actions[bot]@users.noreply.github.com'
          git config --local user.name 'github-actions[bot]'
          git add gen/
          git commit -m 'Update stats and charts' || echo 'No changes to commit'

      - name: Push changes
        run: |
          git push origin main